name: Build and release to Test 🧪

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened, synchronize]
        

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    trigger-build:
        if:
            ${{ !startsWith(github.event.head_commit.message, 'docs')  && !startsWith(github.event.head_commit.message, 'style') && !startswith(github.event.head_commit.message, 'refactor') }}
        secrets: inherit
        uses: equinor/attenuation-app/.github/workflows/build-release-ios.yml@main
        with:
            environment: Prod
